[project]
site_name = "Foundation Legal Codex"
site_url = "https://site-78.github.io/legal-codex"
copyright = "&copy; 2025 Site-78"
    [project.theme]
        features = [
            "navigation.instant",
            "navigation.tracking",
            "navigation.sections",
            "navigation.path",
            "toc.follow",
            "toc.integrate",
            "navigation.top"
        ]
    [project.markdown_extensions]
        [project.markdown_extensions.def_list]
        [project.markdown_extensions.attr_list]
        [project.markdown_extensions.toc]
            permalink =  true
            title = "Table of Contents"
        [project.markdown_extensions.tables]
        [project.markdown_extensions.admonition]
        [project.markdown_extensions.pymdownx.caret]
        [project.markdown_extensions.pymdownx.mark]
        [project.markdown_extensions.pymdownx.tilde]
        [project.markdown_extensions.pymdownx.tabbed]
            alternate_style = true
        
        